# Generated by Django 4.2.12 on 2025-03-02 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('entry_type', models.CharField(choices=[('meal', 'Meal'), ('workout', 'Workout'), ('medical', 'Medical')], max_length=10)),
                ('description', models.TextField()),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_register')),
            ],
        ),
    ]
