# Generated by Django 4.2.12 on 2025-03-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
        migrations.AddField(
            model_name='user_register',
            name='age_range',
            field=models.CharField(blank=True, default='18-25', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_register',
            name='budget_range',
            field=models.CharField(blank=True, default='Low', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_register',
            name='city',
            field=models.CharField(default='Lahore', max_length=100),
        ),
        migrations.AddField(
            model_name='user_register',
            name='first_name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='user_register',
            name='last_name',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='user_register',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user_register',
            name='nationality',
            field=models.CharField(default='Pakistani', max_length=100),
        ),
        migrations.AddField(
            model_name='user_register',
            name='postal_address',
            field=models.TextField(default='123 Default Street'),
        ),
        migrations.AddField(
            model_name='user_register',
            name='preferred_travel_season',
            field=models.CharField(blank=True, default='Summer', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_register',
            name='preferred_travel_type',
            field=models.CharField(blank=True, default='Adventure', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=255),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.DeleteModel(
            name='HealthData',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
