# Generated by Django 4.2.12 on 2025-04-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_destination_latitude_destination_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='activities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
