# Generated by Django 4.2.12 on 2025-04-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_destination_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='last_visited_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_last_visited', to='myapp.destination'),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='age_range',
            field=models.CharField(blank=True, choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-60', '46-60'), ('60+', '60+')], default='18-25', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='budget_range',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='preferred_travel_season',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Autumn', 'Autumn'), ('All Seasons', 'All Seasons')], default='Summer', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='preferred_travel_type',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Relaxation', 'Relaxation'), ('Cultural', 'Cultural'), ('Historical', 'Historical'), ('Nature', 'Nature')], default='Adventure', max_length=50),
        ),
    ]
